spring:
  application:
    name: hospital-in-a-box-backend

  datasource:
    url: jdbc:postgresql://db:5432/hospitaldb
    username: hospital
    password: hospital
  jpa:
    hibernate:
      ddl-auto: update   # for dev; later we can switch to 'validate' + Flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE