FROM node:20-alpine AS build

WORKDIR /app

COPY web/package.json web/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY web/ .
RUN yarn build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 3000
CMD ["yarn", "start"]